[project]
name = "zsynctech-api-robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cachelib>=0.13.0",
    "fastapi[standard]>=0.116.1",
]
