[project]
name = "zsynctech-api-robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "appdirs>=1.4.4",
    "cachelib>=0.13.0",
    "fastapi[standard]>=0.116.1",
    "pika>=1.3.2",
    "python-dotenv>=1.1.1",
]
